In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn import linear_model

In [14]:
raw_data = pd.read_csv("labelled_data.csv")
raw_data.head()

LABEL   FLUX.1   FLUX.2   FLUX.3   FLUX.4   FLUX.5   FLUX.6  FLUX.7  \
0      2    93.85    83.81    20.10   -26.98   -39.56  -124.71 -135.18   
1      2   -38.88   -33.83   -58.54   -40.09   -79.31   -72.81  -86.55   
2      2   532.64   535.92   513.73   496.92   456.45   466.00  464.50   
3      2   326.52   347.39   302.35   298.13   317.74   312.70  322.33   
4      2 -1107.21 -1112.59 -1118.95 -1095.10 -1057.55 -1034.48 -998.34   

    FLUX.8  FLUX.9  ...  FLUX.3188  FLUX.3189  FLUX.3190  FLUX.3191  \
0   -96.27  -79.89  ...     -78.07    -102.15    -102.15      25.13   
1   -85.33  -83.97  ...      -3.28     -32.21     -32.21     -24.89   
2   486.39  436.56  ...     -71.69      13.31      13.31     -29.89   
3   311.31  312.42  ...       5.71      -3.73      -3.73      30.05   
4 -1022.71 -989.57  ...    -594.37    -401.66    -401.66    -357.24   

   FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0      48.57      92.54      39.32      61.42       5.08     -39.54  
1      -4.86       0.76     -11.70       6.46      16.00      19.93  
2     -20.88       5.06     -11.80     -28.91     -70.02     -96.67  
3      20.03     -12.67      -8.77     -17.31     -17.35      13.98  
4    -443.76    -438.54    -399.71    -384.65    -411.79    -510.54  

[5 rows x 3198 columns]

In [87]:
X = raw_data.drop("LABEL", axis=1)
y = raw_data["LABEL"]

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [89]:
smote = SMOTE(sampling_strategy='auto', random_state=36)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [90]:
linear_classifier = linear_model.LinearRegression()
linear_classifier.fit(X_train_resampled, y_train_resampled)

LinearRegression()

In [91]:
y_pred = linear_classifier.predict(X_test)
predicted_labels = np.where(y_pred > 1.4, 2, 1)

In [92]:
accuracy = accuracy_score(y_test, predicted_labels)
print(accuracy)

0.9214145383104125


In [95]:
z = linear_classifier.predict(X_test[y_test == 2])
np.where(z > 1.4, 2, 1)
# z

array([2, 2, 1, 1, 2, 2, 1, 1])

In [96]:
v = linear_classifier.predict(X_train[y_train == 2])
# np.where(v > 1.3, 2, 1)
v

array([1.99979834, 2.00016736, 2.00027556, 1.99965641, 1.99920538,
       1.99956329, 1.99812794, 2.00065746, 1.99978161, 2.00016616,
       1.99984543, 2.00003611, 1.99497865, 2.0007712 , 1.99904117,
       2.00000603, 1.99995037, 1.99981734, 1.99992225, 2.00015914,
       1.99966012, 2.00031775, 1.99935105, 2.00006928, 2.00002617,
       1.99941702, 1.99952486, 2.00016238, 2.00005702])

In [100]:
unlabelled_data = pd.read_csv("unlabelled_data.csv")
unlabelled_data.head()

unlabelled_data.set_index("Serial", inplace = True)
unlabelled_data.head()

FLUX.1   FLUX.2   FLUX.3   FLUX.4   FLUX.5   FLUX.6   FLUX.7  \
Serial                                                                  
0        119.88   100.21    86.46    48.68    46.12    39.39    18.57   
1       5736.59  5699.98  5717.16  5692.73  5663.83  5631.16  5626.39   
2        844.48   817.49   770.07   675.01   605.52   499.45   440.77   
3       -826.00  -827.31  -846.12  -836.03  -745.50  -784.69  -791.22   
4        -39.57   -15.88    -9.16    -6.37   -16.13   -24.05    -0.90   

         FLUX.8   FLUX.9  FLUX.10  ...  FLUX.3188  FLUX.3189  FLUX.3190  \
Serial                             ...                                    
0          6.98     6.63   -21.97  ...      14.52      19.29      14.44   
1       5569.47  5550.44  5458.80  ...    -581.91    -984.09   -1230.89   
2        362.95   207.27   150.46  ...      17.82     -51.66     -48.29   
3       -746.50  -709.53  -679.56  ...     122.34      93.03      93.03   
4        -45.20    -5.04    14.62  ...     -37.87     -61.85     -27.15   

        FLUX.3191  FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  \
Serial                                                                     
0           -1.62      13.33      45.50      31.93      35.78     269.43   
1        -1600.45   -1824.53   -2061.17   -2265.98   -2366.19   -2294.86   
2          -59.99     -82.10    -174.54     -95.23    -162.68     -36.79   
3           68.81       9.81      20.75      20.25    -120.81    -257.56   
4          -21.18     -33.76     -85.34     -81.46     -61.98     -69.34   

        FLUX.3197  
Serial             
0           57.72  
1        -2034.72  
2           30.63  
3         -215.41  
4          -17.84  

[5 rows x 3197 columns]

In [102]:
unlabelled_data.shape

(570, 3197)

In [103]:
pred = linear_classifier.predict(unlabelled_data)
p = np.where(pred>1.4, 2, 1)
p

array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [104]:
unlabelled_data["LABEL"] = p

In [105]:
final_data = unlabelled_data
final_data.head()

FLUX.1   FLUX.2   FLUX.3   FLUX.4   FLUX.5   FLUX.6   FLUX.7  \
Serial                                                                  
0        119.88   100.21    86.46    48.68    46.12    39.39    18.57   
1       5736.59  5699.98  5717.16  5692.73  5663.83  5631.16  5626.39   
2        844.48   817.49   770.07   675.01   605.52   499.45   440.77   
3       -826.00  -827.31  -846.12  -836.03  -745.50  -784.69  -791.22   
4        -39.57   -15.88    -9.16    -6.37   -16.13   -24.05    -0.90   

         FLUX.8   FLUX.9  FLUX.10  ...  FLUX.3189  FLUX.3190  FLUX.3191  \
Serial                             ...                                    
0          6.98     6.63   -21.97  ...      19.29      14.44      -1.62   
1       5569.47  5550.44  5458.80  ...    -984.09   -1230.89   -1600.45   
2        362.95   207.27   150.46  ...     -51.66     -48.29     -59.99   
3       -746.50  -709.53  -679.56  ...      93.03      93.03      68.81   
4        -45.20    -5.04    14.62  ...     -61.85     -27.15     -21.18   

        FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  \
Serial                                                                     
0           13.33      45.50      31.93      35.78     269.43      57.72   
1        -1824.53   -2061.17   -2265.98   -2366.19   -2294.86   -2034.72   
2          -82.10    -174.54     -95.23    -162.68     -36.79      30.63   
3            9.81      20.75      20.25    -120.81    -257.56    -215.41   
4          -33.76     -85.34     -81.46     -61.98     -69.34     -17.84   

        LABEL  
Serial         
0           1  
1           1  
2           1  
3           1  
4           2  

[5 rows x 3198 columns]